version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    tty: true
    command: yarn start:dev
